# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ListApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'Alamofire', '~> 4.8.2'
 pod 'Kingfisher', '~> 4.0'
 pod 'NVActivityIndicatorView'

  # Pods for ListApp

  target 'ListAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
